language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
after_success:
- ./node_modules/.bin/istanbul cover \
  	./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive test && \
  		cat ./coverage/lcov.info | ./bin/coveralls.js --verbose
